import os

class Config:
    SQLALCHEMY_DATABASE_URI = os.getenv('DATABASE_URI')
    if not SQLALCHEMY_DATABASE_URI:
        raise ValueError("DATABASE_URI is not set!")

    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SECRET_KEY = os.getenv('FLASK_APP_SECRET_KEY')
    PAYPAL_CLIENT_ID = os.getenv('PAYPAL_CLIENT_ID')
    EMAILJS_SERVICE_ID = os.getenv('EMAILJS_SERVICE_ID')
    EMAILJS_TEMPLATE_ID_FOR_PAYPAL_CONFIRMATION_EMAIL = os.getenv('EMAILJS_TEMPLATE_ID_FOR_PAYPAL_CONFIRMATION_EMAIL')
    EMAILJS_TEMPLATE_ID_FOR_CONTACT_FORM = os.getenv('EMAILJS_TEMPLATE_ID_FOR_CONTACT_FORM')
    EMAILJS_API_ID = os.getenv('EMAILJS_API_ID')
    RECIPIENT_EMAILS = os.getenv('RECIPIENT_EMAILS')
    PAYPAL_CLIENT_SECRET_KEY = os.getenv('PAYPAL_CLIENT_SECRET_KEY')
    PAYPAL_API_BASE_URL = os.getenv('PAYPAL_API_BASE_URL')