"""Allow donor_email to be NULL

Revision ID: 224230d4f019
Revises: 
Create Date: 2024-10-23 23:30:31.389664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224230d4f019'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.alter_column('donor_email',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.alter_column('donor_email',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    # ### end Alembic commands ###
