"""Fix process_transaction: use DonorItem instead of Donors

Revision ID: 483839a606cf
Revises: 224230d4f019
Create Date: 2024-10-23 23:40:32.461752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483839a606cf'
down_revision = '224230d4f019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_item', schema=None) as batch_op:
        batch_op.alter_column('fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_item', schema=None) as batch_op:
        batch_op.alter_column('fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    # ### end Alembic commands ###
