"""Initial Migration

Revision ID: 483839a606cf
Revises: 
Create Date: 2024-11-08 15:16:08.916821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '483839a606cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_items_id', 'items', ['id'], unique=False)

    op.create_table('donor',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_donor_id', 'donor', ['id'], unique=False)

    op.create_table('donor_item',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('donor_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('item_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(['donor_id'], ['donor.id'], ),
        sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_donor_item_item_id', 'donor_item', ['item_id'], unique=False)
    op.create_index('ix_donor_item_donor_id', 'donor_item', ['donor_id'], unique=False)

    op.create_table('transaction',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('item_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('donor_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('timestamp', sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
        sa.ForeignKeyConstraint(['donor_id'], ['donor.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transaction_item_id', 'transaction', ['item_id'], unique=False)
    op.create_index('ix_transaction_donor_id', 'transaction', ['donor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_donor_id', table_name='transaction')
    op.drop_index('ix_transaction_item_id', table_name='transaction')
    op.drop_table('transaction')

    op.drop_index('ix_donor_item_donor_id', table_name='donor_item')
    op.drop_index('ix_donor_item_item_id', table_name='donor_item')
    op.drop_table('donor_item')

    op.drop_index('ix_donor_id', table_name='donor')
    op.drop_table('donor')

    op.drop_index('ix_items_id', table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
