"""Add GeneralProduct table for Central Park Book and other products

Revision ID: bd873637cb30
Revises: f5a6b7c8d9e0
Create Date: 2025-08-02 22:00:59.122585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd873637cb30'
down_revision = 'f5a6b7c8d9e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('photo', sa.Boolean(), nullable=False),
    sa.Column('imgurl', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('available', 'sold', 'discontinued')", name='check_valid_product_status'),
    sa.CheckConstraint('char_length(name) > 0', name='check_product_name_not_empty'),
    sa.CheckConstraint('fee > 0', name='check_positive_product_fee'),
    sa.CheckConstraint('quantity >= 0', name='check_non_negative_quantity'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('general_products', schema=None) as batch_op:
        batch_op.create_index('idx_general_products_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_general_products_status_type', ['status', 'product_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_general_products_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_general_products_product_type'), ['product_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_general_products_status'), ['status'], unique=False)

    with op.batch_alter_table('bonds', schema=None) as batch_op:
        batch_op.alter_column('front_image',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('back_image',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'available'::text"))
        batch_op.alter_column('vignette',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.drop_index('idx_bonds_status')
        batch_op.drop_index('idx_bonds_type')
        batch_op.create_index(batch_op.f('ix_bonds_issue_date'), ['issue_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bonds_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bonds_type'), ['type'], unique=False)
        batch_op.create_unique_constraint(None, ['bond_id'])

    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.drop_constraint('donors_donor_email_key', type_='unique')
        batch_op.drop_index('idx_donors_email')
        batch_op.drop_index('idx_donors_name')
        batch_op.create_index(batch_op.f('ix_donors_donor_email'), ['donor_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_donors_donor_name'), ['donor_name'], unique=False)
        batch_op.drop_column('street')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('city')
        batch_op.drop_column('state')
        batch_op.drop_column('use_billing_for_shipping')
        batch_op.drop_column('apartment')

    with op.batch_alter_table('historical_records', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('adopted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.drop_index('idx_historical_records_adopted')
        batch_op.drop_index('idx_historical_records_name')
        batch_op.create_index(batch_op.f('ix_historical_records_adopted'), ['adopted'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_records_name'), ['name'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'Completed'::character varying"))
        batch_op.drop_index('idx_transactions_donor_id')
        batch_op.drop_index('idx_transactions_email')
        batch_op.drop_index('idx_transactions_item_id')
        batch_op.drop_index('idx_transactions_paypal_id')
        batch_op.drop_index('idx_transactions_status')
        batch_op.drop_index('idx_transactions_timestamp')
        batch_op.create_index(batch_op.f('ix_transactions_donor_email'), ['donor_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_donor_id'), ['donor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_paypal_transaction_id'), ['paypal_transaction_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_transactions_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_timestamp'))
        batch_op.drop_index(batch_op.f('ix_transactions_paypal_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_payment_status'))
        batch_op.drop_index(batch_op.f('ix_transactions_item_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_donor_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_donor_email'))
        batch_op.create_index('idx_transactions_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('idx_transactions_status', ['payment_status'], unique=False)
        batch_op.create_index('idx_transactions_paypal_id', ['paypal_transaction_id'], unique=False)
        batch_op.create_index('idx_transactions_item_id', ['item_id'], unique=False)
        batch_op.create_index('idx_transactions_email', ['donor_email'], unique=False)
        batch_op.create_index('idx_transactions_donor_id', ['donor_id'], unique=False)
        batch_op.alter_column('payment_status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'Completed'::character varying"))

    with op.batch_alter_table('historical_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_records_name'))
        batch_op.drop_index(batch_op.f('ix_historical_records_adopted'))
        batch_op.create_index('idx_historical_records_name', ['name'], unique=False)
        batch_op.create_index('idx_historical_records_adopted', ['adopted'], unique=False)
        batch_op.alter_column('adopted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('photo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apartment', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('use_billing_for_shipping', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('street', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_donors_donor_name'))
        batch_op.drop_index(batch_op.f('ix_donors_donor_email'))
        batch_op.create_index('idx_donors_name', ['donor_name'], unique=False)
        batch_op.create_index('idx_donors_email', ['donor_email'], unique=False)
        batch_op.create_unique_constraint('donors_donor_email_key', ['donor_email'])

    with op.batch_alter_table('bonds', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_bonds_type'))
        batch_op.drop_index(batch_op.f('ix_bonds_status'))
        batch_op.drop_index(batch_op.f('ix_bonds_issue_date'))
        batch_op.create_index('idx_bonds_type', ['type'], unique=False)
        batch_op.create_index('idx_bonds_status', ['status'], unique=False)
        batch_op.alter_column('vignette',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'available'::text"))
        batch_op.alter_column('back_image',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('front_image',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('general_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_general_products_status'))
        batch_op.drop_index(batch_op.f('ix_general_products_product_type'))
        batch_op.drop_index(batch_op.f('ix_general_products_name'))
        batch_op.drop_index('idx_general_products_status_type')
        batch_op.drop_index('idx_general_products_created_at')

    op.drop_table('general_products')
    # ### end Alembic commands ###